# Generated by Django 4.2.23 on 2025-07-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='description',
            new_name='statement',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='input',
            new_name='expected_output',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='output',
            new_name='input_data',
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
