# Generated by Django 4.2.23 on 2025-07-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_rename_description_problem_statement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='p_id',
            field=models.CharField(default=0, max_length=50, unique=True),
        ),
    ]
