# Generated by Django 4.2.23 on 2025-07-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_problem_tags_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='p_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
