# Generated by Django 4.2.23 on 2025-07-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_alter_problem_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='p_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
