# version: '3.9'

# services:
#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_DB: algoarenadbe
#       POSTGRES_USER: pawni
#       POSTGRES_PASSWORD: pawni3435
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     ports:
#       - "5432:5432"

#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     environment:
#       DATABASE_URL: postgres://pawni:pawni3435@db:5432/algoarenadbe

# volumes:
#   postgres_data:

version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: algoarenadbe
      POSTGRES_USER: pawni
      POSTGRES_PASSWORD: pawni3435
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://pawni:pawni3435@db:5432/algoarenadbe
      DB_HOST: db
      ALLOWED_HOSTS: 0.0.0.0,localhost,127.0.0.1,web,backend-web-1

volumes:
  postgres_data: